# .github/workflows/test-action.yml
name: Email Step Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 23f2000898@ds.study.iitm.ac.in
        run: echo "Hello, world!"
